# Generated by Django 5.2.8 on 2025-12-18 23:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_mapboundary_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bazamocy',
            fields=[
                ('osm_dso_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('oddzial', models.CharField(blank=True, max_length=100, null=True)),
                ('typ', models.CharField(blank=True, max_length=100, null=True)),
                ('layer', models.CharField(blank=True, max_length=100, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=2180)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'data_bazamocy',
                'managed': True,
            },
        ),
    ]
